package org.fundamentals.fp.euler.problem2;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/**
 * https://projecteuler.net/problem=2
 *
 * Original:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *
 * Further information about a Fibonacci serie:
 * https://en.wikipedia.org/wiki/Fibonacci_number
 *
 * Scenario 100:
 *
 * Given a Fibonacci sequence:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * When execute sumEven method
 * Then find the sum of the even-valued terms
 *
 */
public class EulerProblem2 {

    public List<Long> getJavaFibonaccyTerms(long limit) {

        List<Long> fibonacciList = new ArrayList<>();

        long previousNumber = 1;
        long nextNumber = 2;

        for (long i = 1; i <= limit; i++) {

            fibonacciList.add(previousNumber);

            long sum = previousNumber + nextNumber;
            previousNumber = nextNumber;
            nextNumber = sum;
        }

        return fibonacciList;
    }

    public Long javaSolutionFibonacciEvenSum(long limit) {

        List<Long> fibonacciList = this.getJavaFibonaccyTerms(limit);
        long sum = 0L;

        for(long number : fibonacciList) {

            if((number % 2) == 0) {
                sum += number;
            }

        }

        return sum;
    }

    public List<Long> getJavaStreamFibonaccyTerms(long limit) {

        return java.util.stream.Stream.iterate(new Long[]{1L, 2L}, i -> new Long[]{i[1], i[0] + i[1]})
                .limit(limit)
                .map(i -> i[0])
                .collect(Collectors.toList());
    }

    public Long javaStreamSolutionFibonacciEvenSum(long limit) {

        Consumer<Long> print = System.out::println;
        Predicate<Long> isEven = number -> (number % 2) == 0;

        return this.getJavaStreamFibonaccyTerms(limit).stream()
                .filter(isEven)
                //.peek(print)
                .collect(Collectors.summingLong(Long::longValue));
    }

    //Original code: https://github.com/vavr-io/vavr/blob/master/vavr/src/test/java/io/vavr/collection/euler/Utils.java
    public List<Long> getJavaVAVRFibonaccyTerms(long limit) {

        Consumer<Long> print = System.out::println;

        return io.vavr.collection.Stream.of(1L, 2L)
                .appendSelf(self -> self.zip(self.tail())
                .map(t -> t._1 + (t._2)))
                .take((int)limit)
                //.peek(print)
                .collect(Collectors.toList());
    }

    public Long javaVAVRSolutionFibonacciEvenSum(long limit) {

        Consumer<Long> print = System.out::println;
        Predicate<Long> isEven = number -> (number % 2) == 0;

        return this.getJavaVAVRFibonaccyTerms(limit).stream()
                .filter(isEven)
                //.peek(print)
                .collect(Collectors.summingLong(Long::longValue));
    }
}
