package org.fundamentals.fp.euler.problem2;

import java.util.ArrayList;
import java.util.List;

/**
 * https://projecteuler.net/problem=2
 *
 * Original:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *
 * Scenario 100:
 *
 * Given a Fibonacci sequence:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * When execute sumEven method
 * Then find the sum of the even-valued terms
 *
 */
public class EulerProblem2 {

    public List<Long> getJavaFibonaccyTerms(long limit) {

        List<Long> fibonacciList = new ArrayList<>();

        long previousNumber = 1;
        long nextNumber = 2;

        for (long i = 1; i <= limit; i++) {

            fibonacciList.add(previousNumber);

            long sum = previousNumber + nextNumber;
            previousNumber = nextNumber;
            nextNumber = sum;
        }

        return fibonacciList;
    }

    public Long javaSolutionFibonacciEvenSum(long limit) {

        List<Long> fibonacciList = this.getJavaFibonaccyTerms(limit);
        long sum = 0L;

        for(long number : fibonacciList) {

            if((number % 2) == 0) {
                sum += number;
            }

        }

        return sum;
    }
}
