package org.fundamentals.fp.euler;

import java.util.function.Predicate;
import java.util.stream.Collectors;

import io.reactivex.Single;
import reactor.core.publisher.Mono;

/**
 * https://projecteuler.net/problem=2
 *
 * Original:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *
 * Further information about a Fibonacci serie:
 * https://en.wikipedia.org/wiki/Fibonacci_number
 *
 * Scenario 100:
 *
 * Given a Fibonacci sequence:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * When execute sumEven method
 * Then find the sum of the even-valued terms
 *
 */
@Solved
public class EulerProblem02 implements IEulerType1<Long, Long> {

    @Override
    public Long JavaSolution(Long limit) {

        long sum = 0L;
        for (long number : Utils.Java.fibonacci(limit)) {

            if ((number % 2) == 0) {
                sum += number;
            }
        }

        return sum;
    }

    Predicate<Long> isEven = number -> (number % 2) == 0;

    @Override
    public Long JavaStreamSolution(Long limit) {

        return Utils.JavaStreams.fibonacci(limit)
                .filter(isEven)
                .collect(Collectors.summingLong(Long::longValue));
    }

    @Override
    public Long VAVRSolution(Long limit) {

        return Utils.VAVR.fibonacci(limit)
                .filter(isEven)
                .reduce(Long::sum);
    }

    @Override
    public Mono<Long> ReactorSolution(Long limit) {

        return Utils.Reactor.fibonacci(limit)
                .filter(isEven)
                .reduce(Long::sum);
    }

    @Override
    public Single<Long> RxJavaSolution(Long limit) {

        return Utils.RxJava.fibonacci(limit)
                .filter(l -> isEven.test(l))
                .reduce(0L, (a, b) -> a + b);
    }
    
}
